### ISSUE TITLE
missing dependency: therubyracer

### ISSUE THREAD

**Issue by felixge** [zroger/jekyll-less#4]
I followed the instructions and got this warning upon starting jekyll:

```
[WARNING] Please install gem 'therubyracer' to use Less.
```

I guess `therubyracer` should be added as dependency to this project?

**Comment by zroger** [comment]
The less gem depends on the commonjs gem, which is a wrapper for different javascript runtimes.  therubyracer is not the only javascript gem supported, just the suggested one, so it's not really a dependency.

**Comment by felixge** [comment]
Thanks for explaining. I'm not much of a ruby user : ).
